name: elixir-snap
base: core18
version: '1.10.0'
summary: Single-line elevator pitch for your amazing snap
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: stable
confinement: strict

apps:
  elixir:
    command: usr/bin/elixir
  mix:
    command: usr/bin/mix
  elixirc:
    command: usr/bin/elixirc
  iex:
    command: usr/bin/iex

parts:
  elixir:
    plugin: make
    source: https://github.com/elixir-lang/elixir.git
    source-tag: v1.10.0
    build-snaps:
      - erlang
    override-build: |
      set -e -u -x

      make clean
      make compile
      make install PREFIX=/usr DESTDIR=${SNAPCRAFT_PART_INSTALL}
    stage:
      - usr
